
name: goatz_demo
description: GOATZ demo app with local (no backend) data and optional Firebase.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.1.0
  # Uncomment if you connect Firebase for real
  # firebase_core: ^2.24.2
  # cloud_firestore: ^4.15.8
  # firebase_auth: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
